steps:
  - name: 'node:18-alpine'
    args:
      - install
    entrypoint: npm
  - name: 'node:18-alpine'
    args:
      - run
      - build
    entrypoint: npm
  - name: 'node:18-alpine'
    env:
      - HOST=$_HOST
      - PORT=$_PORT
      - TWILIO_AUTH_TOKEN=$_TWILIO_AUTH_TOKEN
      - TWILIO_ACCOUNT_SID=$_TWILIO_AACCOUNT_SID
    args:
      - npm
      - start
    entrypoint: npm
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
